profile-name: "dev"

server:
  port: 8900

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    petkpetk.service: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web.client.RestTemplate: debug

spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  sql:
    init:
      mode: always

  data:
    rest:
      base-path: /api
      detection-strategy: annotated

servlet:
  multipart:
    max-file-size: 20MB
    max-request-size: 100MB

itemImageLocation: "C:/KYE/UploadImages"
uploadPath: "file:///C:/KYE/UploadImages/"



